//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.261
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human80Level.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Human80Level.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выносливость.
        /// </summary>
        public static string AbLisgBtnEndurance {
            get {
                return ResourceManager.GetString("AbLisgBtnEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на интеллект.
        /// </summary>
        public static string AbListBtnIntel {
            get {
                return ResourceManager.GetString("AbListBtnIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удача.
        /// </summary>
        public static string AbListBtnLuck {
            get {
                return ResourceManager.GetString("AbListBtnLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на телосложение.
        /// </summary>
        public static string AbListBtnPhysique {
            get {
                return ResourceManager.GetString("AbListBtnPhysique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сила.
        /// </summary>
        public static string AbListBtnPower {
            get {
                return ResourceManager.GetString("AbListBtnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выберите показатель.
        /// </summary>
        public static string AbListPageTitle {
            get {
                return ResourceManager.GetString("AbListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий уровень.
        /// </summary>
        public static string ALevelLabel {
            get {
                return ResourceManager.GetString("ALevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже использовали свой шанс сегодня.
        /// </summary>
        public static string AlreadyUseCloverMessage {
            get {
                return ResourceManager.GetString("AlreadyUseCloverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на показывает насколько часто обстоятельства складываются в вашу пользу.
        /// </summary>
        public static string ALuckD {
            get {
                return ResourceManager.GetString("ALuckD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы полный неудачник. Даже в списке самых неудачных людей планеты вы на втором месте.
        /// </summary>
        public static string ALuckL1 {
            get {
                return ResourceManager.GetString("ALuckL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учача стоит к вам спиной. .
        /// </summary>
        public static string ALuckL2 {
            get {
                return ResourceManager.GetString("ALuckL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Никогда не знаешь чего ждать от судьбы. Ваши шансы 50/50.
        /// </summary>
        public static string ALuckL3 {
            get {
                return ResourceManager.GetString("ALuckL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удача на вашей стороне. Рекомендуем вам почаще покупать лотерейные билеты.
        /// </summary>
        public static string ALuckL4 {
            get {
                return ResourceManager.GetString("ALuckL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вашему вензению нет предела. Вы можете играть в русскую рулетку с 6 патронами в барабане..
        /// </summary>
        public static string ALuckL5 {
            get {
                return ResourceManager.GetString("ALuckL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы настолько слабы что даже дети могут вас избить.
        /// </summary>
        public static string APower1 {
            get {
                return ResourceManager.GetString("APower1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вас уже не сносит ветром.
        /// </summary>
        public static string APower2 {
            get {
                return ResourceManager.GetString("APower2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы пволне можете постоять за себя.
        /// </summary>
        public static string APower3 {
            get {
                return ResourceManager.GetString("APower3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поединке с терминатором вы вероятно победите.
        /// </summary>
        public static string APower4 {
            get {
                return ResourceManager.GetString("APower4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы Час Норрис.
        /// </summary>
        public static string APower5 {
            get {
                return ResourceManager.GetString("APower5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HUMAN 80 LEVEL.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть клевер.
        /// </summary>
        public static string DefaultEventMessage {
            get {
                return ResourceManager.GetString("DefaultEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на общие сведения.
        /// </summary>
        public static string HelpCommon {
            get {
                return ResourceManager.GetString("HelpCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на гланое меню.
        /// </summary>
        public static string HelpMainMenu {
            get {
                return ResourceManager.GetString("HelpMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на помощь.
        /// </summary>
        public static string HelpPivotTitle {
            get {
                return ResourceManager.GetString("HelpPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на очистить.
        /// </summary>
        public static string LuckPageClearButtonCaption {
            get {
                return ResourceManager.GetString("LuckPageClearButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите событие.
        /// </summary>
        public static string LuckPageMessageBoxCaption {
            get {
                return ResourceManager.GetString("LuckPageMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить событие.
        /// </summary>
        public static string LuckPagePivotAddEvent {
            get {
                return ResourceManager.GetString("LuckPagePivotAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список событий.
        /// </summary>
        public static string LuckPagePivotEventList {
            get {
                return ResourceManager.GetString("LuckPagePivotEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удача.
        /// </summary>
        public static string LuckPagePivotTitle {
            get {
                return ResourceManager.GetString("LuckPagePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытай удачу.
        /// </summary>
        public static string LuckPagePivotTryLuck {
            get {
                return ResourceManager.GetString("LuckPagePivotTryLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты уже использовал свой шанс сегодня.
        /// </summary>
        public static string LuckPageTryLuckAlreadyUsed {
            get {
                return ResourceManager.GetString("LuckPageTryLuckAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угадайте в каком квадрате спрятан клевер.
        /// </summary>
        public static string LuckPageTryLuckLabel {
            get {
                return ResourceManager.GetString("LuckPageTryLuckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на о программе.
        /// </summary>
        public static string MainPageAboutBtn {
            get {
                return ResourceManager.GetString("MainPageAboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на помощь.
        /// </summary>
        public static string MainPageHelpBtn {
            get {
                return ResourceManager.GetString("MainPageHelpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш текущий профиль будет удален всесте с накопленной статистикой. Продолжить?.
        /// </summary>
        public static string MainPageMainPageMBnewProfileMessage {
            get {
                return ResourceManager.GetString("MainPageMainPageMBnewProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите удаление профиля.
        /// </summary>
        public static string MainPageMainPageMBnewProfileTitle {
            get {
                return ResourceManager.GetString("MainPageMainPageMBnewProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на новый профиль.
        /// </summary>
        public static string MainPageNewProfileBtn {
            get {
                return ResourceManager.GetString("MainPageNewProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на начать прокачку.
        /// </summary>
        public static string MainPageStartFlowBtn {
            get {
                return ResourceManager.GetString("MainPageStartFlowBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на статистика.
        /// </summary>
        public static string MainPageStatisticsBtn {
            get {
                return ResourceManager.GetString("MainPageStatisticsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение не может быть пустым.
        /// </summary>
        public static string NullOrEmptyMessageText {
            get {
                return ResourceManager.GetString("NullOrEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string NullOrEmptyMessageTitle {
            get {
                return ResourceManager.GetString("NullOrEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалолсь загрузить профиль.
        /// </summary>
        public static string ProfileMBgetErrorMessage {
            get {
                return ResourceManager.GetString("ProfileMBgetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки профиля.
        /// </summary>
        public static string ProfileMBgetErrorTitle {
            get {
                return ResourceManager.GetString("ProfileMBgetErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес должен быть целым числом.
        /// </summary>
        public static string ProfileMBheightIncorrectMessage {
            get {
                return ResourceManager.GetString("ProfileMBheightIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ProfileMBheightIncorrectTitle {
            get {
                return ResourceManager.GetString("ProfileMBheightIncorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя не может быть пустым.
        /// </summary>
        public static string ProfileMBnickIncorrectMessage {
            get {
                return ResourceManager.GetString("ProfileMBnickIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ProfileMBnickIncorrectTitle {
            get {
                return ResourceManager.GetString("ProfileMBnickIncorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить профиль..
        /// </summary>
        public static string ProfileMBsaveErrorMessage {
            get {
                return ResourceManager.GetString("ProfileMBsaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения.
        /// </summary>
        public static string ProfileMBsaveErrorTitle {
            get {
                return ResourceManager.GetString("ProfileMBsaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес не может быть меньше нуля.
        /// </summary>
        public static string ProfileMBsubzeroheighMessage {
            get {
                return ResourceManager.GetString("ProfileMBsubzeroheighMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ProfileMBsubzeroheighTitle {
            get {
                return ResourceManager.GetString("ProfileMBsubzeroheighTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения были успешно сохранены.
        /// </summary>
        public static string ProfileMBupdateMessage {
            get {
                return ResourceManager.GetString("ProfileMBupdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль обновлен.
        /// </summary>
        public static string ProfileMBupdateTitle {
            get {
                return ResourceManager.GetString("ProfileMBupdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на галерея.
        /// </summary>
        public static string ProfilePageBtnAlbum {
            get {
                return ResourceManager.GetString("ProfilePageBtnAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на камера.
        /// </summary>
        public static string ProfilePageBtnCamera {
            get {
                return ResourceManager.GetString("ProfilePageBtnCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пустой.
        /// </summary>
        public static string ProfilePageBtnEmpty {
            get {
                return ResourceManager.GetString("ProfilePageBtnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сохранить.
        /// </summary>
        public static string ProfilePageBtnSave {
            get {
                return ResourceManager.GetString("ProfilePageBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата рождения.
        /// </summary>
        public static string ProfilePageTextBirth {
            get {
                return ResourceManager.GetString("ProfilePageTextBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на рост.
        /// </summary>
        public static string ProfilePageTextHeight {
            get {
                return ResourceManager.GetString("ProfilePageTextHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на имя.
        /// </summary>
        public static string ProfilePageTextNickname {
            get {
                return ResourceManager.GetString("ProfilePageTextNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выбери аватар.
        /// </summary>
        public static string ProfilePageTextSelectAvatar {
            get {
                return ResourceManager.GetString("ProfilePageTextSelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие будет удалено. Продолжить?.
        /// </summary>
        public static string RemoveEventMessageText {
            get {
                return ResourceManager.GetString("RemoveEventMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите удаление.
        /// </summary>
        public static string RemoveEventMessageTitle {
            get {
                return ResourceManager.GetString("RemoveEventMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на показатели.
        /// </summary>
        public static string StatPagePivotCommonItem {
            get {
                return ResourceManager.GetString("StatPagePivotCommonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на история.
        /// </summary>
        public static string StatPagePivotHistoryItem {
            get {
                return ResourceManager.GetString("StatPagePivotHistoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на статистика.
        /// </summary>
        public static string StatPagePivotTitle {
            get {
                return ResourceManager.GetString("StatPagePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие добавлено.
        /// </summary>
        public static string SuccessAddMessage {
            get {
                return ResourceManager.GetString("SuccessAddMessage", resourceCulture);
            }
        }
    }
}
