//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.261
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human80Level.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Human80Level.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже использовали свой шанс сегодня.
        /// </summary>
        public static string AlreadyUseCloverMessage {
            get {
                return ResourceManager.GetString("AlreadyUseCloverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть клевер.
        /// </summary>
        public static string DefaultEventMessage {
            get {
                return ResourceManager.GetString("DefaultEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на очистить.
        /// </summary>
        public static string LuckPageClearButtonCaption {
            get {
                return ResourceManager.GetString("LuckPageClearButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите событие.
        /// </summary>
        public static string LuckPageMessageBoxCaption {
            get {
                return ResourceManager.GetString("LuckPageMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить событие.
        /// </summary>
        public static string LuckPagePivotAddEvent {
            get {
                return ResourceManager.GetString("LuckPagePivotAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список событий.
        /// </summary>
        public static string LuckPagePivotEventList {
            get {
                return ResourceManager.GetString("LuckPagePivotEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удача.
        /// </summary>
        public static string LuckPagePivotTitle {
            get {
                return ResourceManager.GetString("LuckPagePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытай удачу.
        /// </summary>
        public static string LuckPagePivotTryLuck {
            get {
                return ResourceManager.GetString("LuckPagePivotTryLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты уже использовал свой шанс сегодня.
        /// </summary>
        public static string LuckPageTryLuckAlreadyUsed {
            get {
                return ResourceManager.GetString("LuckPageTryLuckAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угадайте в каком квадрате спрятан клевер.
        /// </summary>
        public static string LuckPageTryLuckLabel {
            get {
                return ResourceManager.GetString("LuckPageTryLuckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение не может быть пустым.
        /// </summary>
        public static string NullOrEmptyMessageText {
            get {
                return ResourceManager.GetString("NullOrEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string NullOrEmptyMessageTitle {
            get {
                return ResourceManager.GetString("NullOrEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие будет удалено. Продолжить?.
        /// </summary>
        public static string RemoveEventMessageText {
            get {
                return ResourceManager.GetString("RemoveEventMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите удаление.
        /// </summary>
        public static string RemoveEventMessageTitle {
            get {
                return ResourceManager.GetString("RemoveEventMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие добавлено.
        /// </summary>
        public static string SuccessAddMessage {
            get {
                return ResourceManager.GetString("SuccessAddMessage", resourceCulture);
            }
        }
    }
}
